### ISSUE TITLE
ERD 설계

### ISSUE THREAD

**Issue by jhpa0308** [Team-PATCH/Harmony-Server#4]
## 🤷‍♂️ Description
- Harmony의 데이터베이스 구조를 설계하기 위한 ERD를 작성합니다.
- 이 ERD는 사용자, 기억 카드, 채팅 세션, 일정 등의 주요 엔티티와 그들 간의 관계를 포함합니다.

## ❗️Requirements
- [x] 사용자(Users) 엔티티 정의 (보호자/피보호자 구분 포함)
- [x] 기억 카드(MemoryCards) 엔티티 및 관련 엔티티 정의
- [x] 채팅 세션(ChatSessions) 및 메시지(ChatMessages) 엔티티 정의
- [x] 일과(Routines) 및 반응(RoutineReactions) 엔티티 정의
- [ ] 일정(Schedules) 엔티티 정의
- [x] 질문(Questions) 엔티티 정의
- [x] 모든 엔티티 간의 관계 정의 (1:N, N:M 등)
- [x] 각 엔티티의 주요 속성 정의
- [x] Primary Key 및 Foreign Key 명시
- [x] 식별/비식별 관계 구분

## ✳️ Remarks
- ERD 툴: ERD Cloud 사용
- 데이터베이스: MySQL
- 향후 확장성을 고려하여 설계할 것
- 개인정보 보호를 위한 데이터 암호화 방식 논의 필요
- 대용량 데이터 처리를 위한 인덱싱 전략 고려 필요

**Comment by WaterBean** [comment]
강사님께 피드백 받은내용 반영해 ERD 완성
